global class GatewayResponse {
	global Datetime gatewayDate;
	global String gatewayReferenceDetails;
	global String gatewayReferenceNumber;
	global String gatewayResultCode;
	global String gatewayResultCodeDescription;
	global GatewayResponse() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}