global class ProductFile {
	global ConnectApi.ProductCollateralType collateralType;
	global ConnectApi.ProductFileFormat fileFormat;
	global String fileUrl;
	global String id;
	global String recordId;
	global String title;
	global ProductFile() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}