global class ProductImage {
	global String description;
	global String id;
	global String imageAlternateText;
	global String imageGroup;
	global String imageTitle;
	global String imageUrl;
	global ConnectApi.ProductImageViewType imageViewType;
	global Boolean isActive;
	global String recordId;
	global Integer sequence;
	global ProductImage() { }
	global Object clone() { }
	global Boolean equals(Object obj) { }
	global Double getBuildVersion() { }
	global Integer hashCode() { }
	global String toString() { }

}