global class Decimal {
	public Decimal abs() {}
	public Decimal divide(Decimal divisor, Integer scale) {}
	public Decimal divide(Decimal divisor, Integer scale, System.RoundingMode roundingMode) {}
	public Double doubleValue() {}
	public String format() {}
	public Integer intValue() {}
	public Long longValue() {}
	public Decimal pow(Integer exponent) {}
	public Integer precision() {}
	public Long round() {}
	public Long round(System.RoundingMode roundingMode) {}
	public Integer scale() {}
	public Decimal setScale(Integer scale) {}
	public Decimal setScale(Integer scale, System.RoundingMode roundingMode) {}
	public Decimal stripTrailingZeros() {}
	public static Decimal valueOf(Double doubleToDecimal) {}
	public static Decimal valueOf(Long longToDecimal) {}
	public static Decimal valueOf(String stringToDecimal) {}

}