global class Map {
	public Void clear() {}
	public Map<Object, Object> clone() {}
	public Boolean containsKey(Object key) {}
	public Map<Object, Object> deepClone() {}
	public Boolean equals(Map map2) {}
	public Object get(Object key) {}
	public Schema.SObjectType getSObjectType() {}
	public Integer hashCode() {}
	public Boolean isEmpty() {}
	public Set<Object> keySet() {}
	public Object put(Object key, Object value) {}
	public Void putAll(Map fromMap) {}
	public Void putAll(sObject[] sobjectArray) {}
	public Object remove(Key key) {}
	public Integer size() {}
	public String toString() {}
	public List<Object> values() {}	
}