public class HardcodedSecretTest1 {

	public static final String AWS_SECRET_KEY = 'AKIALALEMEL33243OLIA';

	public void foo1() {
		for (Opportunity o : [select id from Opportunity]) {
			if (true) {
				return;
			}
		}
	}

	public void foo2() {
		for (RecordType rt : items) {
			recordTypeMap.put(rt.DeveloperName, rt.id);
			if (x.Id == '0FM30000000014C') {
				List<Opportunity> myList = [select id from Opportunity];
				delete [select id from Opportunity];
			}
		}
	}

}
